[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'python -m uvicorn src.api.main:app --host 0.0.0.0 --port $PORT --workers 2 --timeout-keep-alive 300'"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ALWAYS"

# Performance optimizations
[env]
# Database connection pool settings
DB_MIN_CONNECTIONS = "5"
DB_MAX_CONNECTIONS = "50"
# Sync operation timeouts
SYNC_TIMEOUT_SECONDS = "600"
# Railway function timeout handling
RAILWAY_TIMEOUT_SECONDS = "300" 