[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PORT = "8000"
PYTHONPATH = "/app/src" 